/**
 * Pipes' own systemd unit content is generated by vehicle-server's shared
 * generateSystemdUnit -- this only proves pipesServiceSpec() feeds it the
 * right values, not the generator's own behavior (covered directly in
 * vehicle-server's own test suite). No real systemctl call: that's a
 * genuine mutation of the operator's own systemd --user session, not
 * something a test should ever do.
 */
import { describe, expect, it } from "bun:test";
import { generateSystemdUnit } from "@danypops/vehicle-server/service";
import { pipesServiceSpec } from "../../src/cli/index.ts";

describe("Pipes systemd service", () => {
	it("runs `pipes serve` with no extra args", () => {
		const spec = pipesServiceSpec();
		expect(spec.args).toEqual([expect.stringContaining("cli"), "serve"]);
	});

	it("declares restartOnFailure -- Pipes' own client never auto-spawns the daemon, so systemd is its only recovery path", () => {
		const unit = generateSystemdUnit(pipesServiceSpec());
		expect(unit).toContain("Restart=always");
		expect(unit).toContain("RestartSec=2");
	});

	it("names the unit and descriptor after pipes, matching constants.ts's SYSTEMD_UNIT_NAME", () => {
		const spec = pipesServiceSpec();
		expect(spec.name).toBe("pipes");
		expect(spec.descriptorPath).toContain("pipes");
	});
});

describe("pipes service (real subprocess): usage", () => {
	it("exits non-zero with usage for a missing or unrecognized action", async () => {
		const cliPath = new URL("../../src/cli/index.ts", import.meta.url).pathname;
		const proc = Bun.spawn(["bun", cliPath, "service", "bogus"], { stdout: "pipe", stderr: "pipe" });
		const [stderr, code] = await Promise.all([new Response(proc.stderr).text(), proc.exited]);
		expect(code).not.toBe(0);
		expect(stderr).toContain("usage: pipes service <install|start|stop|restart|status>");
	});
});
